apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Release.Namespace }}
    server: {{ include "server.url" . }}
  project: {{ .Values.project }}
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: {{ .Values.path }}
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
  syncPolicy:
    automated: {}
